### ISSUE TITLE
Debian repository configuration is lacking TLS usage

### ISSUE THREAD

**Issue by kholia** [elastic/ansible-beats#2]
The `tasks/beats-debian.yml` file uses plain HTTP URLs (e.g. http://packages.elasticsearch.org/GPG-KEY-elasticsearch).

This is not entirely safe. Usage of HTTPS URLs is strongly recommended.

Thanks!

**Comment by ypid-geberit** [comment]
> Usage of HTTPS URLs is strongly recommended.

Either that or pin the OpenPGP fingerprint like this:

https://github.com/debops/debops/blob/d9713de0f2d9b0be8c0d553bc8ec47f9a1dd6835/ansible/roles/debops.elastic_co/tasks/main.yml#L4-L5

https://github.com/debops/debops/blob/d9713de0f2d9b0be8c0d553bc8ec47f9a1dd6835/ansible/roles/debops.elastic_co/defaults/main.yml#L43

The pinning has additional benefits because what should the OpenPGP key actually protect against? -> Compromised webservers in case we already have TLS. Ref: https://github.com/jchaney/owncloud/pull/12

**Comment by jmlrt** [comment]
fixed by https://github.com/elastic/ansible-beats/pull/10
